job:
    pattern:  /
    defaults: { _controller: "ComoJobeetBundle:Job:index" }

job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "ComoJobeetBundle:Job:show" }
    requirements:
        id:  \d+

job_new:
    pattern:  /new
    defaults: { _controller: "ComoJobeetBundle:Job:new" }

job_create:
    pattern:  /create
    defaults: { _controller: "ComoJobeetBundle:Job:create" }
    requirements: { _method: post }

job_edit:
    pattern:  /{token}/edit
    defaults: { _controller: "ComoJobeetBundle:Job:edit" }

job_update:
    pattern:  /{token}/update
    defaults: { _controller: "ComoJobeetBundle:Job:update" }
    requirements: { _method: post }

job_delete:
    pattern:  /{token}/delete
    defaults: { _controller: "ComoJobeetBundle:Job:delete" }
    requirements: { _method: post }
    
job_preview:
    pattern:  /{company}/{location}/{token}/{position}
    defaults: { _controller: "ComoJobeetBundle:Job:preview" }
    requirements:
        token:  \w+
        
job_publish:
    pattern:  /{token}/publish
    defaults: { _controller: "ComoJobeetBundle:Job:publish" }
    requirements: { _method: post }